# GitHub Sponsors + 즉시 사용 가능한 대안
# GitHub Sponsors 승인되면 주 플랫폼으로 사용

github: bellkjtt  # 승인 대기 중 (1-3일 소요)

# 즉시 사용 가능한 대안 (선택)
# ko_fi: bellkjtt  # Ko-fi 가입 후 활성화
# custom: ["https://buymeacoffee.com/bellkjtt"]  # Buy Me a Coffee

# 사용 방법:
# 1. Ko-fi나 Buy Me a Coffee에 가입
# 2. 위 줄의 주석(#) 제거
# 3. git push
# 4. 즉시 "Sponsor" 버튼 활성화!
